services:
  db:
    image: mysql:9.4.0-oracle
    container_name: db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
    volumes:
      - ../app/backend/init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "status", "-h", "localhost", "-u", "root", "-p${DB_ROOT_PASSWORD}"]
      interval: 10s
      timeout: 10s
      retries: 3
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin:5.2.2
    container_name: phpmyadmin
    ports:
      - 3001:80
    depends_on:
      db:
        condition: service_healthy

  php-apache:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: php
    ports:
      - 3000:80
    volumes:
      - ../app/frontend:/var/www/html
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    depends_on:
      db:
        condition: service_healthy

  
