name: container-health-check.yml
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  check-containers:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Go to Docker Directory
        run: cd docker

      - name: Start docker compose
        run: docker compose up -d

      - name: Wait for containers to start
        run: sleep 5

      - name: Check if all the containers are running
        run: docker compose ps

      - name: Stop containers
        run: docker compose down
