name: container-health-check.yml
on:
  push:
    branches:
      - 'main'
  pull_request:

jobs:
  check-containers:
    runs-on: ubuntu-latest
    env:
      DB_ROOT_PASSWORD: test123
      DB_USER: testuser
      DB_PASSWORD: testpass
      DB_NAME: finance_app_db
      DB_HOST: db
    steps:
      - uses: actions/checkout@v4

      - name: Start docker compose
        run: docker compose -f docker/docker-compose.yaml up -d

      - name: Wait for containers to start
        run: sleep 15

      - name: Check if all the containers are running
        run: docker compose -f docker/docker-compose.yaml ps

      - name: Stop containers
        run: docker compose -f docker/docker-compose.yaml down
